# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    #csrf_protection: true
    #http_method_override: true

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    session:
        handler_id: session.handler.native_file
        cookie_lifetime: 172800
        cookie_secure: 'auto'
        cookie_samesite: 'lax'
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
        storage_factory_id: session.storage.factory.native

    #esi: true
    #fragments: true
    php_errors:
        log: true
