version: '3.7'
services:
  wsexport:
    build:
      context: .
      args:
        USER_ID: ${WS_DOCKER_UID}
        GROUP_ID: ${WS_DOCKER_GID}
    ports:
      - "${WS_EXPORT_PORT:-8888}:8080"
    extra_hosts:
      - "host.docker.internal:host-gateway"  
    volumes:
      - ../:/var/www/html:cached
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf:cached
      - ./apache/ports.conf:/etc/apache2/ports.conf:cached
      - ./php.ini:/usr/local/etc/php/php.ini:cached
    links:
      - database:database
    environment:
      - APACHE_RUN_USER=daemon
      - XDEBUG_MODE=off
    depends_on:
      - database
  database:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=1
      - MYSQL_DATABASE=wsexport
